name: Generate Stats SVGs
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch: # Manual trigger
jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Stats
        run: |
          curl "https://github-readme-stats.vercel.app/api?username=MohdArshad-cell&show_icons=true&theme=tokyonight&hide_border=true" > github-stats.svg
          curl "https://github-readme-stats.vercel.app/api/top-langs/?username=MohdArshad-cell&layout=compact&theme=tokyonight&hide_border=true" > top-langs.svg
      - name: Commit Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.svg
          git commit -m "System Telemetry: Infrastructure Update" || exit 0
          git push
